import './globals.css'

export const metadata = {
  title: 'Ecommerce Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header>This is the Header</header>
        {children}
      <footer>This is the Footer</footer>
        </body>
    </html>
  )
}
